set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'a.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'airblade/vim-gitgutter'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'Valloric/YouCompleteMe'

Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'

Plugin 'kien/ctrlp.vim'
Plugin 'rking/ag.vim'
Plugin 'tpope/vim-commentary'
Plugin 'bling/vim-airline'
Plugin 'Raimondi/delimitMate'
Plugin 'tpope/vim-fugitive'

Plugin 'fatih/vim-go'
Plugin 'majutsushi/tagbar'

Plugin 'hynek/vim-python-pep8-indent'

call vundle#end()
filetype plugin indent on

"set rtp+=/usr/local/opt/go/libexec/misc/vim/

let mapleader = ","

if has("gui_running")
  if has("gui_gtk2")
    set guifont=Pragmata\ Pro\ 12
  else
    set guifont=PragmataPro:h12
  endif
endif

set ignorecase "Ignore case when searching
set smartcase
set hlsearch "Highlight search things
set incsearch "Make search act like search in modern browsers

set showmatch "Show matching bracets when text indicator is over them
set mat=2 "How many tenths of a second to blink

set wildmenu

syntax enable

colorscheme desert
set background=dark
set t_Co=256

set nu

if has("gui_running")
  set guioptions-=T
endif

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Files, backups and undo
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Turn backup off, since most stuff is in SVN, git anyway...
set nobackup
set nowb
set noswapfile

"Persistent undo
try
    if MySys() == "windows"
      set undodir=C:\Windows\Temp
    else
      set undodir=~/.vim_runtime/undodir
    endif

    set undofile
catch
endtry

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Text, tab and indent related
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set noexpandtab                         " use tabs, not spaces
set tabstop=8                           " tabstops of 8
set shiftwidth=8                        " indents of 8
set textwidth=158                       " screen in 80 columns wide, wrap at 158

set autoindent smartindent              " turn on auto/smart indenting
set smarttab                            " make <tab> and <backspace> smarter
set backspace=eol,start,indent          " allow backspacing over indent, eol, & start

let NERDTreeIgnore = ['\.pyc$', '\.o$', '\.lo$']

set foldmethod=marker

map <Leader>n <plug>NERDTreeTabsToggle<CR>
nnoremap <leader>jd :YcmCompleter GoTo<CR>

let g:UltiSnipsExpandTrigger="<c-j>"

nmap <F8> :TagbarToggle<CR>

let g:go_fmt_command = "goimports"
